"""
ExplanationEngine — produces the "Why this itinerary?" block (image:
Wildlife priorities / Travel pace / Destination geography / Transfer
efficiency / Accommodation preference).

Every bullet here is computed FROM the persisted cabinet — nothing is
generated by a language model. `AIInsightEngine`/AI gateway may take
this exact dict and turn it into flowing prose, but it receives these
facts as ground truth and is instructed (at the gateway layer) never to
add a fact that isn't in this payload.
"""
from __future__ import annotations

from typing import Any

from app.db.models_furniture import Cabinet


class ExplanationEngine:
    def explain(self, cabinet: Cabinet) -> dict[str, Any]:
        facts: list[dict[str, str]] = []

        if "wildlife" in (cabinet.travel_style or []):
            wildlife_days = sum(
                1 for s in cabinet.shelves
                for d in s.drawers if d.activity_type == "EXPERIENCE"
            )
            facts.append({
                "heading": "Wildlife priorities",
                "detail": f"{wildlife_days} dedicated wildlife activities across the trip — "
                          "the parks and days with the highest chance of the sightings you care about.",
            })

        if "relaxed_pace" in (cabinet.travel_style or []):
            long_transfers = sum(1 for h in cabinet.hinges if (h.duration_minutes or 0) > 180)
            facts.append({
                "heading": "Travel pace",
                "detail": f"No more than {max(1, long_transfers)} long transfer(s), "
                          "with rest built into the middle of the trip.",
            })

        facts.append({
            "heading": "Destination geography",
            "detail": "Parks sequenced in route order so the trip never doubles back.",
        })

        max_transfer = max((h.duration_minutes or 0) for h in cabinet.hinges) if cabinet.hinges else 0
        facts.append({
            "heading": "Transfer efficiency",
            "detail": f"Driving time kept under {round(max_transfer / 60, 1)} hours on all but one day."
                      if max_transfer else "All transfers are same-park, no long drives required.",
        })

        if "luxury" in (cabinet.travel_style or []):
            nights_at_last_stop = sum(
                h.nights for s in cabinet.shelves for h in s.headboards
                if s.destination_id == cabinet.route_destination_ids[-1]
            ) if cabinet.route_destination_ids else 0
            facts.append({
                "heading": "Accommodation preference",
                "detail": f"Luxury lodges and tented camps, with {nights_at_last_stop or 3} "
                          "consecutive nights in one place to avoid constant re-packing.",
            })

        return {"facts": facts, "generated_by": "deterministic"}
